# Generated by Django 2.2 on 2019-05-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sports',
            name='img',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='sports',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
