# Generated by Django 2.2 on 2019-05-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterpage', '0003_entertainment_politics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Editorials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('img', models.ImageField(upload_to='images/')),
                ('description', models.TextField()),
            ],
        ),
    ]
